sudo: false
language: node_js
node_js:
  - "6"
  - "5"
  - "4"

services:
  - docker

before_install:
  - docker pull influxdb:0.13-alpine
  - docker run -d -p 8086:8086 influxdb:0.13-alpine
  - docker run -d -p 8085:8086 -e INFLUXDB_HTTP_AUTH_ENABLED=true influxdb:0.13-alpine

script:
  - npm test

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls