[[http]]
name = "influxdb-relay"
bind-addr = "0.0.0.0:9096"
output = [
  { name = "influxdb-1:", location = "http://influxdb-1:8086/write", buffer-size-mb = 100, max-batch-kb = 50, max-delay-interval = "5s", timeout = "10s" },
  { name = "influxdb-2", location = "http://influxdb-2:8086/write", buffer-size-mb = 100, max-batch-kb = 50, max-delay-interval = "5s", timeout = "10s" },
]
